; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Sep 04 2020 17:50:14 GMT+0200 (Mitteleuropäische Sommerzeit)

