; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Sun May 29 2022 19:46:45 GMT+0200 (Mitteleuropäische Sommerzeit)
; Wait for set temperatures to be reached
M116 P0

